### ISSUE TITLE
support for iOS App

### ISSUE THREAD

**Issue by muhanadali100** [streamaserver/streama-app#5]
Please realase to apple phone

ipa

**Comment by muhanadali100** [comment]
set Allow anonymous access to the application

**Comment by dularion** [comment]
i did, but the videos still wont play :( any suggestion?

**Comment by muhanadali100** [comment]
Redirect the links of movie to work on the vlc program it supports all formats

**Comment by muhanadali100** [comment]
?

**Comment by dularion** [comment]
You cannot simply redirect the links to  vlc. You would have to let the user download the videos first, which does not seem like a good idea on smartphones, due to limited disk space and limited bandwidth. The html5 player streams the video, only fetching a few bytes at a time, which is a lot more mobile-friendly. I can publish the current state of the app to the ios store soon-ish. But apple requires a login etc. I gotta setup a demo site first.
